{{- if and (not .Values.database.existingSecret) .Values.database.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "civicgrid-api.databaseSecretName" . }}
  labels:
    {{- include "civicgrid-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
{{- if and (not .Values.admin.existingSecret) .Values.admin.token -}}
{{- if .Values.database.url }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "civicgrid-api.adminSecretName" . }}
  labels:
    {{- include "civicgrid-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.admin.token | quote }}
{{- end }}
